
stages:
  - build
  - deploy
  - security-scan

variables:
  DOCKER_DRIVER: overlay2

build_docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t myapp ./app

deploy_ansible:
  stage: deploy
  image: python:3.10
  before_script:
    - pip install ansible docker
  script:
    - cd ansible
    - ansible-playbook -i inventory/hosts site.yml

deploy_terraform:
  stage: deploy
  image: hashicorp/terraform:light
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
trivy_scan:
  image:
    name: aquasec/trivy:latest
  stage: security-scan
  script:
    - trivy image your-image-name:latest

semgrep_scan:
  image:
    name: returntocorp/semgrep
  stage: security-scan
  script:
    - semgrep --config=auto .